3dollar-in-my-pocket/3dollar-in-my-pocket-android

app/src/main/java/com/zion830/threedollars/customview/NaverMapFragment.kt
app/src/main/java/com/zion830/threedollars/ui/category/StreetByMenuFragment.kt
app/src/main/java/com/zion830/threedollars/ui/category/TruckByMenuFragment.kt
app/src/main/java/com/zion830/threedollars/ui/food_truck_store_detail/FoodTruckStoreDetailActivity.kt
app/src/main/java/com/zion830/threedollars/ui/report_store/map/StoreEditNaverMapFragment.kt
app/src/main/java/com/zion830/threedollars/ui/store_detail/StoreCertificationAvailableFragment.kt
app/src/main/java/com/zion830/threedollars/ui/store_detail/StoreCertificationFragment.kt
app/src/main/java/com/zion830/threedollars/ui/store_detail/StoreDetailActivity.kt
app/src/main/java/com/zion830/threedollars/ui/store_detail/map/StoreCertificationNaverMapFragment.kt
app/src/main/java/com/zion830/threedollars/ui/store_detail/map/StreetStoreByMenuNaverMapFragment.kt
app/src/main/java/com/zion830/threedollars/ui/store_detail/map/TruckStoreByMenuNaverMapFragment.kt
common.gradle

파이어 베이스 크래시에서 네이버 맵 에러가 나는 문제
버그가 구현은 안되지만 fragment에 인자를 넣어서 생기는 문제로 추정돼서 수정

hoxfix 3.0.1

---

app/src/debug/google-services.json

FireBase Dev 추가하였습니다.
체크해봐야할 점이 있습니다. 일단 Debug Hash Key로인해서 저나 민호님만 될수도 있어요.
혹여 그렇다면 Dev용 keystore를 만들어서 Hash Key 등록하고 배포할때 Keystore이용해서 debug 배포를 해야 할 수도 있습니다.

[Feat] Firebase Json 파일 Dev 폴더에 추가

---

app/src/main/java/com/zion830/threedollars/datasource/MyReviewDataSourceImpl.kt
app/src/main/java/com/zion830/threedollars/datasource/MyStoreDataSourceImpl.kt
app/src/main/java/com/zion830/threedollars/datasource/MyVisitHistoryDataSourceImpl.kt
app/src/main/java/com/zion830/threedollars/di/NetworkModule.kt

Hilt로 의존성을 주입하는 방식으로 업데이트 하면서 생긴 문제입니다.
paging에 Hilt로 의존성을 주입하려면 구조를 바꿔야 할꺼 같습니다.
시간이 조금 걸릴 작업 일꺼 같아서 newServiceApi를 호출하는 방식으로 먼저 수정 했습니다.

[Fix] 내가 쓴 리뷰 / 최근 들린 가게 / 제보한 가게 데이터 안나오는 문제 수정

---

app/src/main/java/com/zion830/threedollars/datasource/model/v2/response/PopupsResponse.kt
app/src/main/java/com/zion830/threedollars/network/NewServiceApi.kt
app/src/main/java/com/zion830/threedollars/ui/category/StreetByMenuFragment.kt
app/src/main/java/com/zion830/threedollars/ui/category/StreetSelectCategoryDialogFragment.kt
app/src/main/java/com/zion830/threedollars/ui/category/TruckByMenuFragment.kt
app/src/main/java/com/zion830/threedollars/ui/category/TruckSelectCategoryDialogFragment.kt
app/src/main/java/com/zion830/threedollars/ui/home/HomeFragment.kt
app/src/main/java/com/zion830/threedollars/ui/popup/PopupFragment.kt
app/src/main/java/com/zion830/threedollars/ui/popup/PopupViewModel.kt
common/src/main/java/zion830/com/common/ext/StringExt.kt

확장함수로 `toStringDefault` 추가하였습니다.
nullable한 string인경우 null일때 기본값을 추가하거나 기본값으로 공백을 return을 해주도록 만들었습니다.
추후에 int 등 여러 자료형들에도 추가해서 가능한 null에 문제생기지 않도록 만들면 좋을 것 같아요.

[Feat] popups data nullable 처리 및 string null default 확장함수 추가

---

app/src/main/java/com/zion830/threedollars/ui/map/NaverMapFragment.kt
common.gradle

- 광고용 마커 사이즈 고정 가로 44dp 세로 48dp
- 버전 업 3.1.1

[Fix] 광고용 마커 사이즈 고정 및 버전 업데이트

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/zion830/threedollars/DeepLinkInfo.kt
app/src/main/java/com/zion830/threedollars/DynamicLinkActivity.kt
app/src/main/java/com/zion830/threedollars/GlobalApplication.kt
app/src/main/java/com/zion830/threedollars/ui/favorite/FavoriteMyFolderActivity.kt
app/src/main/java/com/zion830/threedollars/ui/favorite/FavoriteViewModel.kt
app/src/main/java/com/zion830/threedollars/ui/favorite/viewer/FavoriteBindingAdapter.kt
app/src/main/java/com/zion830/threedollars/ui/favorite/viewer/FavoriteViewerActivity.kt
app/src/main/res/layout/activity_dynamiclink.xml
app/src/main/res/layout/activity_favorite_my_folder.xml
app/src/main/res/layout/item_favorite_viewer.xml
common.gradle
common/src/main/java/zion830/com/common/base/BaseBindingAdapter.kt

#82 
즐겨찾기 공유하기 버튼 구현 
공유하기 다이나믹 링크 생성 및 공유 구현
#84 #85 #86 , 승호님이 슬랙으로 말씀해주신 여러번 클릭시 공유가 여러개 뜨는 문제
더블클릭 방지하다보니 기존에있던 onSingleClick이 정상 동작하지 않은걸 발견했습니다.
- 클릭할때마다 매번 새로 생성하면서 `OnSingleClickListener`해당 class에 있는 `lastClickTime`이 매번 0임
그래서 일단 임시방편으로 처리해두었는데 나중에 제대로 정리가 필요할 것 같아요. 일단 그대로 사용해도 되긴합니다.

[Feat] 즐겨찾기 공유하기 버튼 구현

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/zion830/threedollars/DynamicLinkActivity.kt
app/src/main/java/com/zion830/threedollars/MainActivity.kt
app/src/main/java/com/zion830/threedollars/ui/favorite/viewer/FavoriteViewerActivity.kt
app/src/main/java/com/zion830/threedollars/ui/food_truck_store_detail/FoodTruckStoreDetailActivity.kt
app/src/main/java/com/zion830/threedollars/ui/mypage/MyPageFragment.kt
app/src/main/java/com/zion830/threedollars/ui/mypage/vm/MyPageViewModel.kt
app/src/main/java/com/zion830/threedollars/ui/splash/SplashActivity.kt
app/src/main/java/com/zion830/threedollars/ui/store_detail/StoreDetailActivity.kt
app/src/main/java/com/zion830/threedollars/utils/SystemUtils.kt
app/src/main/java/com/zion830/threedollars/utils/ThreedollarsMessagingService.kt
common.gradle
common/src/main/java/zion830/com/common/base/BaseActivity.kt

- 푸시를 통한 딥링크 적용했습니다.
- 개발 딥링크 스키마와 프로덕션 딥링크 스키마를 나누었습니다.
- 개발: dollars-dev://{path}
- 프롣거션: dollars://{path}
- 알림권한 요청 추가 필요

[Feat] DeepLink 작업 완료, 버전 업데이트

---

app/src/main/java/com/zion830/threedollars/MainActivity.kt
app/src/main/java/com/zion830/threedollars/utils/SystemUtils.kt

[Feat] 13버전 알림 권한 요청

---

app/src/main/java/com/zion830/threedollars/ui/food_truck_store_detail/FoodTruckStoreDetailActivity.kt
common.gradle

- 기존에 딥링크 처리하면서 Main으로 보내는 처리를 하면서 생긴 문제입니다.

[Feat] 사장님 가게 리뷰남기기 오류 수정

---

app/src/main/java/com/zion830/threedollars/ui/write/ui/NewAddressFragment.kt
app/src/main/res/layout/fragment_mypage_setting.xml
app/src/main/res/navigation/mobile_navigation.xml
common.gradle

- 설정에 로딩 visible 변경
- 가게제보 상세화면 네비게이션 연결 
- 버전업
- 긴급이라 먼저 올렸습니다. 소스는 천천히 확인해보셔도 될 것 같아요

[Feat] 버전업 및 무한로딩제거, 가게제보상세 추가

---

app/src/main/java/com/zion830/threedollars/MainActivity.kt
app/src/main/java/com/zion830/threedollars/ui/map/ui/NaverMapFragment.kt
app/src/main/java/com/zion830/threedollars/ui/popup/PopupFragment.kt
app/src/main/java/com/zion830/threedollars/ui/splash/viewModel/SplashViewModel.kt
app/src/main/java/com/zion830/threedollars/utils/SystemUtils.kt
community/presentation/src/main/java/com/threedollar/presentation/poll/PollDetailActivity.kt
core/common/src/main/java/com/threedollar/common/base/BaseActivity.kt

- https://console.firebase.google.com/project/dollar-in-my-pocket/crashlytics/app/android:com.zion830.threedollars/issues/bd23df52eb8a8783a1f1d05d788e5df4?hl=ko&time=last-seven-days&types=crash&versions=4.0.3%20(73)&sessionEventKey=6582560F035F000119B57611E7E50FD4_1892949026729684017
- https://console.firebase.google.com/project/dollar-in-my-pocket/crashlytics/app/android:com.zion830.threedollars/issues/3bd414335858853e4c58526fedd4a220?hl=ko&time=last-seven-days&types=crash&versions=4.0.3%20(73)&sessionEventKey=6585640600CA0001442CC71C8AFBE758_1893809139254506276
- https://console.firebase.google.com/project/dollar-in-my-pocket/crashlytics/app/android:com.zion830.threedollars/issues/7ff4298da71d715d2df5cb0cedec59d9?hl=ko&time=last-seven-days&types=crash&versions=4.0.3%20(73)&sessionEventKe …

[Feat] 크래시리포트 정리 12월23일

---

app/src/main/java/com/zion830/threedollars/DynamicLinkActivity.kt

- 지정되어 있지 않은 link일 경우 main으로 이동

[Feat] 푸시 발송시 link: ""로 발송시, 앱이 종료되는 버그 대응

---

app/src/main/java/com/zion830/threedollars/ui/dialog/MarketingDialog.kt
app/src/main/java/com/zion830/threedollars/ui/home/ui/HomeFragment.kt
app/src/main/java/com/zion830/threedollars/ui/mypage/ui/MyPageSettingFragment.kt
app/src/main/java/com/zion830/threedollars/utils/LegacySharedPrefUtils.kt
app/src/main/java/com/zion830/threedollars/utils/SystemUtils.kt

- 파이어베이스 구독 및 첫 진입 처리
- 각 마수동 관련 구독 로직 추가

TH-90 파이어베이스 푸시 (마케팅/푸시 알림 설정 필터링 적용)

---

app/build.gradle
app/debug/output-metadata.json
app/src/main/java/com/zion830/threedollars/ui/home/adapter/AroundStoreMapViewRecyclerAdapter.kt
app/src/main/java/com/zion830/threedollars/ui/home/ui/HomeFragment.kt
app/src/main/java/com/zion830/threedollars/ui/storeDetail/boss/ui/BossStoreDetailActivity.kt
app/src/main/java/com/zion830/threedollars/ui/storeDetail/user/ui/StoreDetailActivity.kt
app/src/main/res/layout/activity_food_truck_store_detail.xml
app/src/main/res/layout/activity_store_info.xml
app/src/main/res/layout/fragment_home_list_view.xml
app/src/main/res/layout/item_near_store_ad.xml
app/src/main/res/values/strings.xml
community/presentation/build.gradle
community/presentation/src/main/java/com/threedollar/presentation/CommunityFragment.kt
community/presentation/src/main/java/com/threedollar/presentation/poll/PollDetailActivity.kt
community/presentation/src/main/res/layout/activity_poll_detail.xml
community/presentation/src/main/res/layout/fragment_community.xml
community/presentation/src/main/res/values/strings.xml
home/domain/src/main/java/com/home/domain/data/advertisement/AdvertisementModelV2Empty.kt

- 유저 가게 상세
- 커뮤니티 탭
- 투표 상세
- 홈 카드
애드몹 추가

[Feat] 애드몹 추가

---

app/src/main/java/com/zion830/threedollars/ui/home/adapter/RecentSearchAdapter.kt
app/src/main/java/com/zion830/threedollars/ui/home/ui/HomeFragment.kt
app/src/main/java/com/zion830/threedollars/ui/home/ui/SearchAddressFragment.kt
app/src/main/java/com/zion830/threedollars/ui/home/viewModel/SearchAddressViewModel.kt
app/src/main/res/drawable/ic_address_result.xml
app/src/main/res/drawable/ic_close_gray.xml
app/src/main/res/drawable/ic_close_white.xml
app/src/main/res/layout/fragment_search_by_address.xml
app/src/main/res/layout/item_recent_search.xml
core/network/src/main/java/com/threedollar/network/api/ServerApi.kt
core/network/src/main/java/com/threedollar/network/data/place/Content.kt
core/network/src/main/java/com/threedollar/network/data/place/Cursor.kt
core/network/src/main/java/com/threedollar/network/data/place/Location.kt
core/network/src/main/java/com/threedollar/network/data/place/PlaceResponse.kt
core/network/src/main/java/com/threedollar/network/request/PlaceRequest.kt
core/network/src/main/java/com/threedollar/network/request/PlaceType.kt
core/network/src/main/java/com/threedollar/network/util/ServerUtil.kt
home/data/src/main/java/com/home/data/HomeMapper.kt
home/data/src/main/java/com/home/data/datasource/HomeRemoteDataSource.kt
home/data/src/main/java/com/home/data/datasource/HomeRemoteDataSourceImpl.kt
home/data/src/main/java/com/home/data/datasource/PlacePagingDataSource.kt
home/data/src/main/java/com/home/data/repository/HomeRepositoryImpl.kt
home/domain/src/main/java/com/home/domain/data/place/PlaceModel.kt
home/domain/src/main/java/com/home/domain/repository/HomeRepository.kt
home/domain/src/main/java/com/home/domain/request/PlaceRequest.kt
home/domain/src/main/java/com/home/domain/request/PlaceType.kt

- 주소 검색 시 최근 검색어 노출과 삭제 기능을 추가 했습니다.

[Th 118] 최근 검색어 노출/삭제 기능

---

app/src/main/java/com/zion830/threedollars/ui/storeDetail/boss/ui/BossStoreDetailActivity.kt

- 피드백 개수를 카운트 하는 방식을 변경하여 오류를 수정 했습니다.

[Fix] - 사장님 가게 피드백 개수 오류 수정

---

app/src/main/java/com/zion830/threedollars/ui/home/adapter/AroundStoreMapViewRecyclerAdapter.kt
app/src/main/res/layout/fragment_home.xml

- 홈 화면 카드 카테고리 최대 3개까지 보이게 수정
- 필터 끝부분 위치 수정

Th 203 208 aos

---

app/src/main/java/com/zion830/threedollars/ui/home/adapter/AroundStoreMapViewRecyclerAdapter.kt
app/src/main/java/com/zion830/threedollars/ui/splash/ui/SplashActivity.kt
app/src/main/res/layout/item_near_store_ad.xml

- 광고사이즈 수정
지라 - https://3dollarinmypocket.atlassian.net/browse/TH-240

[Feat] 광고 사이즈 수정

---

app/src/main/java/com/zion830/threedollars/ui/home/ui/HomeListViewFragment.kt
app/src/main/java/com/zion830/threedollars/ui/map/ui/StoreCertificationNaverMapFragment.kt

- 가게리스트에 리스트 광고로 변경
- https://console.firebase.google.com/u/0/project/dollar-in-my-pocket/crashlytics/app/android:com.zion830.threedollars/issues/7bf660cae29a7d871fcd9c964bf644a6?time=last-seven-days&types=crash&sessionEventKey=67306B4D016000010317AEAC0A58EFF7_2014006566447337495 처리

[TH-419] 가게리스트 광고 수정

---

my/presentation/src/main/java/com/my/presentation/page/screen/MyPageScreen.kt

[TH-314] 이미지 shape 변경

---

app/src/main/java/com/zion830/threedollars/di/LegacyNetworkModule.kt

- 레거시 모듈에서만 가져다써서 새로운 모듈과 동일하게 하드코딩으로 변경

[TH-435] 레거시 모듈 user agent 하드코딩

---

community/presentation/src/main/res/layout/dialog_neighbor_choice.xml

[TH-382] 인기 가게 동네리스트 짤림 수정

---

app/src/main/java/com/zion830/threedollars/ui/storeDetail/user/ui/StoreDetailActivity.kt
app/src/main/java/com/zion830/threedollars/ui/write/adapter/PhotoRecyclerAdapter.kt
home/data/src/main/java/com/home/data/HomeMapper.kt

[TH-380] 가게 상세 리뷰 카운트 수정

---

my/presentation/src/main/java/com/my/presentation/page/screen/MyPageScreen.kt

- API 맞게 리컴포지션으로 변경 
https://github.com/user-attachments/assets/24c9a8c1-6e1c-45d1-854a-a8feb0717431

[TH-325] API에 맞는 리컴포지션 구현

---

app/src/main/java/com/zion830/threedollars/ui/mypage/ui/MyPageSettingFragment.kt
app/src/main/java/com/zion830/threedollars/utils/SystemUtils.kt
app/src/main/res/layout/fragment_mypage_setting.xml
app/src/main/res/values/strings.xml
common/src/main/res/drawable/ic_switch_off.xml
common/src/main/res/drawable/ic_switch_on.xml
common/src/main/res/drawable/selector_switch.xml

- 마케팅 수신동의 알럿 추가
- 토스트 추가
- 영역 변경 스위치 -> 전체
https://github.com/user-attachments/assets/bdbee812-063d-46cf-8ff8-cf07b559adaf

[TH-329] 마케팅 수신 동의 OFF시 알럿 추가

---

app/src/main/java/com/zion830/threedollars/ui/home/ui/HomeFragment.kt
app/src/main/java/com/zion830/threedollars/ui/home/ui/HomeListViewFragment.kt
app/src/main/java/com/zion830/threedollars/ui/home/ui/SearchAddressFragment.kt
app/src/main/java/com/zion830/threedollars/ui/home/viewModel/HomeViewModel.kt
app/src/main/java/com/zion830/threedollars/ui/map/ui/NearStoreNaverMapFragment.kt
app/src/main/java/com/zion830/threedollars/ui/write/ui/EditAddressFragment.kt
app/src/main/java/com/zion830/threedollars/ui/write/ui/NewAddressFragment.kt
app/src/main/java/com/zion830/threedollars/ui/write/viewModel/AddStoreViewModel.kt
app/src/main/java/com/zion830/threedollars/utils/NaverMapUtils.kt
home/data/src/main/java/com/home/data/datasource/HomeRemoteDataSource.kt
home/data/src/main/java/com/home/data/datasource/HomeRemoteDataSourceImpl.kt
home/data/src/main/java/com/home/data/repository/HomeRepositoryImpl.kt
home/domain/src/main/java/com/home/domain/repository/HomeRepository.kt

- 현위치 기준 가게로드시 좌상단, 우하단 거리계산 추가

[TH-381] 좌상단, 우하단 거리 계산 후 추가

---

app/src/main/java/com/zion830/threedollars/ui/dialog/AddStoreMenuCategoryDialogFragment.kt
app/src/main/java/com/zion830/threedollars/ui/dialog/SelectCategoryDialogFragment.kt
app/src/main/java/com/zion830/threedollars/ui/home/adapter/SelectCategoryRecyclerAdapter.kt
app/src/main/java/com/zion830/threedollars/ui/popup/PopupViewModel.kt
app/src/main/java/com/zion830/threedollars/ui/write/adapter/AddCategoryRecyclerAdapter.kt
app/src/main/res/layout/item_category_btn.xml
community/domain/src/main/java/com/threedollar/domain/data/AdvertisementModelV2.kt
core/common/src/main/java/com/threedollar/common/utils/AdvertisementsPosition.kt
home/domain/src/main/java/com/home/domain/data/store/CategoryModel.kt

[Feat] - 카테고리 리스트 아이콘 광고 / 앱 스킴 구현

---

app/src/main/java/com/zion830/threedollars/ui/home/ui/HomeListViewFragment.kt
app/src/main/java/com/zion830/threedollars/ui/home/viewModel/HomeViewModel.kt
app/src/main/res/layout/item_list_view_ad.xml
core/common/src/main/java/com/threedollar/common/base/ResponseWrapper.kt

[TH-458] 리펙토링 및 광고 타이틀영역 수정

---

app/src/main/java/com/zion830/threedollars/ui/dialog/SelectCategoryDialogFragment.kt

[TH-464] 광고 클릭시 카테고리 dismiss

---

app/src/main/java/com/zion830/threedollars/MainActivity.kt
core/common/src/main/java/com/threedollar/common/utils/GlobalEvent.kt
core/network/src/main/java/com/threedollar/network/di/NetworkModule.kt

[TH-459] 글로벌 이벤트 추가하여 401이벤트 인터셉트

---

home/data/src/main/java/com/home/data/datasource/HomeRemoteDataSourceImpl.kt

[TH-501] distanceM 조건 추가

---

app/src/main/java/com/zion830/threedollars/MainActivity.kt
app/src/main/java/com/zion830/threedollars/ui/splash/ui/SplashActivity.kt

- 로그인시 세션에러 안나게 수정
- mainactivity flow 라이프사이클 수정, navcontroler 접근시점 잘못됨

[TH-503] 로그인시 세션에러 제거 및 MainActivity Flow 라이프사이클 수정

---

app/src/main/java/com/zion830/threedollars/ui/dialog/SelectCategoryDialogFragment.kt

[Feat] - 카테고리 광고 아이콘 없을 시 튕기는 문제 수정

---

app/src/main/java/com/zion830/threedollars/MainActivity.kt

- 팝업 `collect`가 `STARTED`에 있어서 생긴 문제였습니다.

[Feat] - 전면 배너가 홈 화면 올 때 마다 표시되는 문제 해결

---

app/src/main/java/com/zion830/threedollars/ui/home/adapter/AroundStoreListViewRecyclerAdapter.kt
app/src/main/java/com/zion830/threedollars/ui/home/ui/HomeListViewFragment.kt
app/src/main/res/layout/item_list_view_empty.xml

- 리스트뷰에서 방문 인증 기능이 동작하지 않는 문제 수정
- 빈 리스트일 때 공백으로 광고가 표시되는 문제 수정

[Feat] - 리스트뷰 방문 인증 기능 버그 수정

---

app/src/main/java/com/zion830/threedollars/ui/home/adapter/AroundStoreListViewRecyclerAdapter.kt
app/src/main/java/com/zion830/threedollars/ui/home/adapter/AroundStoreMapViewRecyclerAdapter.kt
app/src/main/java/com/zion830/threedollars/ui/storeDetail/boss/ui/BossStoreDetailActivity.kt
app/src/main/java/com/zion830/threedollars/ui/storeDetail/user/ui/StoreDetailActivity.kt
app/src/main/res/layout/activity_food_truck_store_detail.xml
app/src/main/res/values/strings.xml
core/common/src/main/java/com/threedollar/common/utils/Constants.kt
core/common/src/main/java/com/threedollar/common/utils/Utils.kt
core/common/src/main/res/values/strings.xml
core/network/src/main/java/com/threedollar/network/data/store/BossStore.kt
core/network/src/main/java/com/threedollar/network/data/store/ContactsNumber.kt
home/data/src/main/java/com/home/data/HomeMapper.kt
home/domain/src/main/java/com/home/domain/data/store/BossStoreModel.kt

- 가게까지의 거리 표기 개선 (1km 넘어가면 최대 1km+로 표기 중 -> 최대 10km+로 증가)
지라 - https://3dollarinmypocket.atlassian.net/browse/TH-551

[TH-551] 가게까지의 거리 표기 개선
